version: '3.8'

services:
  # PHP Service
  app:
    image: abirzishan32/task4_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task4_app
    restart: unless-stopped
    environment:
      - APP_ENV=prod
      - APP_SECRET=${APP_SECRET}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "80:8069"
    volumes:
      - symfony_var:/var/www/symfony/var
      - symfony_public:/var/www/symfony/public
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: task4_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3369"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  symfony_var:
  symfony_public:
  db_data: