
services:
  # MySQL Service
  db:
    image: mysql:8.0
    container_name: task4_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 3369:3306
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network
  # PHP Service
  app:
    depends_on:
      - db
    image: abirzishan32/task4_app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task4_app
    restart: unless-stopped
    ports:
      - 8069:80
    volumes:
      - symfony_var:/var/www/symfony/var
      - symfony_public:/var/www/symfony/public
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  symfony_var:
  symfony_public:
  db_data: